POST http://eventhub.local/api/events/
Content-Type: application/json

{
    "title": "Concert",
    "description": "Concert à Paris de jsp",
    "date": "2026-04-21T20:00:00",
    "status": "active"
}

###
GET  http://eventhub.local/api/events/

###
DELETE http://eventhub.local/api/events/2/

###
PUT http://eventhub.local/api/events/3/
Content-Type: application/json

{
    "title": "Séance cinéma",
    "description": "Séance Marty Supreme",
    "date": "2026-04-21T20:00:00",
    "status": "active"
}

###
PATCH http://eventhub.local/api/events/3/
Content-Type: application/json

{
    "status": "inactive"
}

###
POST http://eventhub.local/api/auth/login/
Content-Type: application/json

{
    "username": "admintest",
    "password": "admintest"
}

###
GET  http://eventhub.local/api/registrations/

###
GET http://eventhub.local/api/events/4/
