apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      initContainers:
        - name: migrate
          image: valentinng00/event-service
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for postgres..."
              until nc -z postgres-service 5432; do
                sleep 2
              done
              echo "Postgres is up"
              python manage.py migrate
      containers:
        - name: event-service
          image: valentinng00/event-service:5
          imagePullPolicy: Always
